25.08.2017 11:25:29
System.Data.SqlClient.SqlException (0x80131904): В базе данных уже существует объект с именем "tbl_Territory_tracking".
   в System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   в System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   в System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   в System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   в System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   в System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   в System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   в SyncSQL.Sync.Provision.UpdateExistingScopeProvision(SqlSyncScopeProvisioning provision, SqlConnection conn, Boolean isServer) в c:\Temp\github\SyncSQL\SyncSQL\Sync\Provision.cs:строка 121
   в SyncSQL.Sync.Provision.Run() в c:\Temp\github\SyncSQL\SyncSQL\Sync\Provision.cs:строка 45
   в SyncSQL.Program.Main(String[] args) в c:\Temp\github\SyncSQL\SyncSQL\Program.cs:строка 16
ClientConnectionId:9f4aea34-d605-4221-b558-04f525c980df
Error Number:2714,State:6,Class:16